
version: 2
jobs:
  build:
    docker:
      - image: sleavely/node-awscli:14.x
    working_directory: ~/slowcoder.com
    steps:
      - checkout
      - run:
          name: Install Hexo CLI
          command: npm install -g hexo-cli
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: npm-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Generate static website
          command: hexo generate
      # - run:
      #     name: Install AWS CLI
      #     command: |
      #       apt-get update
      #       apt-get install -y awscli
      - run:
          name: Push to S3 bucket
          command: cd public/ && aws s3 sync . s3://lukayeh.com
      - run:
          name: Invalidate Distribution 
          command: aws cloudfront create-invalidation --distribution-id=E2ABXXWA8SYGVO --paths /